Add movie suggestions to movie_details using the KNN recommendation model
ContriHUB/MovieScreen pull request #35
Opened 2024-10-27 09:10 UTC by Aryan10

## Description

Integrated the KNN-based recommendation system that suggests similar movies to a particular move based on genre with the web page to show recommendations. This is a revised version of PR #33

The new approach differs a bit as suggested by #31 Instead of searching for movie name in the local dataset, it uses the genres generated by API, maps them to genres in the dataset to use the KNN model for predicitons, this makes suggestions immediately avaliable for all movies. Further, posters of those movies are searched from the OMDB API and displayed on the movie_details page.

## Related Issue

Fixes #31 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

This feature allows users to see movie recommendations based on the current movie they’re viewing, enhancing user engagement.

## How Has This Been Tested?

The feature was manually tested in the development environment to verify:

- The similarity recommendations display correctly for each movie
- No errors occur when movies with no recommendations are encountered
- Template renders without layout or display issues
- Posters are fetched and display correctly from the OMDB api

## Screenshots:
<details>
<summary>
Recommendations for Interstellar

Genre: Adventure, Drama, Sci-Fi
</summary>

![image](https://github.com/user-attachments/assets/6eeabc35-4893-4956-8903-f594541b9dc4)

![image](https://github.com/user-attachments/assets/605675dd-5cb8-46fc-a19d-c4e3a8ca792f)

</details>

<details>
<summary>
Recommendations for Shrek

Genre: Animation, Adventure, Comedy
</summary>

![image](https://github.com/user-attachments/assets/3152cfd3-75e9-4005-9900-991cd08e83f4)

![image](https://github.com/user-attachments/assets/151b6417-6b22-4f2f-8ec8-76a01e82aab0)

</details>

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-10-27 09:12 UTC, Aryan10 commented
@eleensmathew Please verify if this contains everything.

2024-10-27 09:14 UTC, eleensmathew commented
Lgtm but i still need to check on my device. I'll review the pr and check it out

2024-10-27 09:15 UTC, Aryan10 commented
Also ma'am you might need to reject the old PR on ContriHUB site so I submit another one (can not request assignment atm).

2024-10-27 09:16 UTC, eleensmathew commented
No need to request, i'll just review this pr and after merging I'll just accept the pr submitted on the website

2024-10-27 09:17 UTC, Aryan10 commented
Ok got it.

2024-10-27 14:25 UTC, eleensmathew requested changes

2024-10-27 14:25 UTC, eleensmathew commented on notebook/recommendation.py
> +# In[81]:
remove these comments

2024-10-27 14:25 UTC, eleensmathew commented on notebook/recommendation.py
> +# In[82]:
remove these comments

2024-10-27 14:25 UTC, eleensmathew commented on notebook/recommendation.py
> +(movies.shape)
these lines are not required here

2024-10-27 14:25 UTC, eleensmathew commented on notebook/recommendation.py
> +data.head()
not required here

2024-10-27 14:25 UTC, eleensmathew commented on notebook/recommendation.py
> +recommend_similar_movies_model1("Toy Story (1995)")
remove this line

2024-10-27 14:31 UTC, Aryan10 commented
I have removed those comments and also pushed some code in styles.css in line with the original design

![image](https://github.com/user-attachments/assets/5722721f-3475-4a4a-9bc7-b3ba68251d49)

2024-10-28 15:39 UTC, eleensmathew commented
![Uploading image.png…]()
Can you change it so that if a picture isnt found a default pic is shown?

2024-10-28 16:56 UTC, Aryan10 commented
@eleensmathew Can you give me an example where this happens so I can test it?

2024-10-28 17:00 UTC, Aryan10 commented
Ok wait I was able to find an example, I will add a default image for when no image is found.

2024-10-28 17:11 UTC, Aryan10 commented
@eleensmathew I have added the placeholder image, please take a look

2024-10-28 17:12 UTC, Aryan10 commented
![image](https://github.com/user-attachments/assets/a3742cd6-aadd-4477-bdf0-21838614932a)

2024-10-29 14:38 UTC, Aryan10 commented
@eleensmathew Have you looked into this? Or do I need to make any more changes.

2024-10-29 14:54 UTC, eleensmathew commented
No need for more changes

2024-10-29 16:46 UTC, eleensmathew commented
The placeholder image works fine but the styling in the web page appears like this rn to me 
![image](https://github.com/user-attachments/assets/5ba77090-798a-4bef-89b9-c84e40af0a7b)

I think you have added styling here right?

2024-10-29 17:05 UTC, eleensmathew commented
Also can you resolve the conflicts

2024-10-29 17:48 UTC, Aryan10 commented
Ok I will resolve the conflicts, I think its mostly just import statements wait

2024-10-29 18:06 UTC, Aryan10 commented
@eleensmathew I have resolved the merge conflicts and tested the site

2024-10-29 19:17 UTC, Aryan10 commented
@eleensmathew for the styling, it looks correct to me, have you tried reloading with Ctrl+F5?

2024-10-29 19:18 UTC, eleensmathew commented
I'll check it again

2024-10-29 19:18 UTC, Aryan10 commented
@eleensmathew Ok wait I will also re check, I noticed the structure of css was changed a bit

2024-10-29 19:23 UTC, eleensmathew commented
Hey it looks good now. I will merge it

2024-10-29 19:24 UTC, merged